language: dart
dart:
  - stable
addons:
  postgresql: "9.6"

services:
  - postgresql

before_install:
  - bash ci/before_install.sh

after_success:
  - bash ci/after_script.sh

jobs:
  include:
    - stage: test
      script: bash ci/script.sh

stages:
  - test

branches:
  only:
    - master
