name: store_server
description: Back-end de loja online de instrumentos.
version: 0.0.1
author: Wígny Almeida <wignybora@gmail.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: ^3.0.0

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0